run:
  timeout: 10m
  skip-dirs:
    - vendor
    - third_party
    - pkg/client
  modules-download-mode: vendor

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - asciicheck
    - errorlint
    - gofumpt
    - gosec
    - govet
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - unconvert

linters-settings:
  staticcheck:
    go: '1.17'
  stylecheck:
    checks:
      - all
      - -ST1000
