apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: addressableservices.samples.knative.dev
  labels:
    samples.knative.dev/release: devel
    knative.dev/crd-install: "true"
